<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <ProjectReference Include="../SwiftBets.Payments.Domain/SwiftBets.Payments.Domain.csproj" />
  </ItemGroup>
</Project>
